### ISSUE TITLE
Playing single tracks doesn't work

### ISSUE THREAD

**Issue by boedy** [gilbarbara/react-spotify-web-playback#19]
First of all: Great player component you've made here!

Currently it's not possible to play a single track uri, because of this line:
https://github.com/gilbarbara/react-spotify-web-playback/blob/b6d26a11c38bd53e49df7325de7f3c8aadae8e9e/src/index.tsx#L244

Is there a purpose for the `ids.length > 1` check?

**Comment by gilbarbara** [comment]
Hey @boedy 

I can't remember why this check is present. I'll take a look.

**Comment by alexnguyen98** [comment]
@gilbarbara 
There reason might be that your using context_uri (which is used for albums/playlists/artists) instead of uris (for tracks).
I might switch to uris for single track usage.

https://github.com/spotify/web-api/issues/675
https://developer.spotify.com/documentation/web-api/reference/player/start-a-users-playback/
--

**Comment by gilbarbara** [comment]
@alexnguyen98 
It's already using URIs for tracks. The API won't work any other way...

**Comment by gilbarbara** [comment]
hey @boedy 

I've updated the URI parsing and validation. There's a preview if you want to test it: https://nwl9c.csb.app/

Here's the list of changes: https://github.com/gilbarbara/react-spotify-web-playback/pull/20 for this version.
I still have some UIs updates to finish before I publish it but it shouldn't tell take long.

**Comment by gilbarbara** [comment]
Fixed in 0.7.0
