### ISSUE TITLE
Songs not loaded when player is paused

### ISSUE THREAD

**Issue by landon-baker** [gilbarbara/react-spotify-web-playback#2]
Hello! This is an amazing library and I really appreciate all of the work you have put into this! The only question I have/issue I see is about the player behavior when it is paused. 

URI changes are handled wonderfully while the player is currently playing, however it seems that when the player is paused and new URIs are passed down, the player is unresponsive. It would be great if the player began autoplaying the newly passed URIs when it is updated or if the URIs were queued and accessible when the next track is activated.

Steps to reproduce in the published [demo](https://react-spotify-web-playback.gilbarbara.dev/):
1. When the autoplay starts for the album, pause the player.
2. Click `play an artist` - the player remains unaffected, but new URIs are passed down
3. Resume play. Skip to the next track. The album is still playing.
4. Click `play an artist` again - the player still remains unaffected because the URIs have not changed - they were changed in step 2.
5. Click the next track button in the player - the original album is still playing
6. The only way to switch to playing the artist is to click on one of the other 3 options (album, playlist, or tracks) and then click back onto the artist. The URIs that were passed in step 2 are never played/accessible.

Is there currently any support for this functionality that I am missing? If I understand it correctly, it seems that the only way to change the track is to make sure that the player is currently playing a track.

Thank you!

**Comment by gilbarbara** [comment]
@landon-baker Hey Landon! Thanks! <3
I'll take a look at this over the weekend.

**Comment by gilbarbara** [comment]
The only way to load URIs in the player is with the [play](https://developer.spotify.com/documentation/web-api/reference-beta/#endpoint-start-a-users-playback) endpoint and that's why it didn't honor the URIs changes while paused.
I've added a flag to update the context if URIs have changed while the player was paused in v0.6.0

I've changed the demo to play automatically when clicking the buttons but it worked without autoplay anyway.

Thanks

**Comment by landon-baker** [comment]
Sorry, but would you mind sharing how you updated the demo? That's exactly what I'm looking to do, but I'm not clear on exactly what you did.

Could you also elaborate a bit on the callback prop - how it's used and maybe a quick example? That would be very helpful!

Thanks again!

**Comment by gilbarbara** [comment]
@landon-baker 

You can check this [codesandbox](https://codesandbox.io/s/react-spotify-web-playback-demo-dye1g) for the demo source code.
**Since the preview panel runs on an iframe, the player DOESN'T work with it.**
That's why the demo isn't hosted there and you must open the preview in a new window to work.

The `callback` prop doesn't need to be used unless you want to listen to player updates. If you open the dev tools in the demo you'll see it's content.
I use it to identify when the player throws an **authentication error**, that most likely means the token has expired...

In this app I'm working on, https://musicbot.io/, I use the callback to control the card play status.

**Comment by nisargshh** [comment]
Off-topic, for musicbot did you get the written permission from Spotify to get the access token so you don't have to update it every hour?

**Comment by gilbarbara** [comment]
@nisargshh I have to update the token when it expires, I just use the user refresh_token.
