### ISSUE TITLE
i have dounghts about how update the token..

### ISSUE THREAD

**Issue by mayander30** [gilbarbara/react-spotify-web-playback#23]
after the token expiry, error appear, have a way for change token?

**Comment by gilbarbara** [comment]
Hey,

This library isn't responsible for handling tokens.
You can watch for the `authentication_error` in the callback and refresh the token by yourself.

Check the demo source for an example.

**Comment by mayander30** [comment]
you should receive a function instead of a token string

Your player
`this.player = new window.Spotify.Player({
      getOAuthToken: (cb: (token: string) => void) => {
        cb(token);
      },
      name,
    }) as IWebPlaybackPlayer;`

Solution
`playerRef.current = new window.Spotify.Player({
        name,
        getOAuthToken: async (cb) => {
          const token = await refresh(acc);
          cb(token);
        },
      });`

in this way the sdk automatically updates the token.

**Comment by gilbarbara** [comment]
hey,

The initialization happens just once when the page loads and the token will expire in one hour.
The `getOAuthToken` wouldn't run again.
https://developer.spotify.com/documentation/web-playback-sdk/reference/
Do you have additional (and official) documentation explaining your suggestion?

This library isn't handling the token fetching and Spotify authentication flow since different apps would need different implementations.

**Comment by mayander30** [comment]
sure, but the refresh funcion it is my, when sdk need a new token, it run getOauthToken again.
it is working for me.
