### ISSUE TITLE
need some additional clarity when no uris are provided. 

### ISSUE THREAD

**Issue by caranicas** [gilbarbara/react-spotify-web-playback#48]
On initial load the callback function fires twice with 2 `status_update`s. once with `INITIALIZING` , and then `READY` however this `READY` will fire regardless of if there are default URIs provided. and with the same data shape as when then a URI is provided. 

This means that the a user can click on the play button and they will be greeted with this text in the player `Cannot perform operation; no list was loaded.` But that doesn't actually fire an event, so I have no way to know that the user needs assistance. to guide them on how to connect.

One thing I was thinking I could do is track the URIs internally, and use CSS to disable the play buttons, and give the user some instruction for how to connect to the Spotify player, but there is no callback for that, so I would never know that they completed it.  I thought perhaps if I used syncExternalDevice I would get some additional callbacks but that didn't work.

So I am hoping that there is away to add that and/or have the `READY`  status let me know that I don't have any URIs

please let me know if there is some other way to accomplish what I have set forth. 

thanks

**Comment by gilbarbara** [comment]
hey @caranicas 

Both `status_update` is related to the Spotify Web Player SDK load.
Wouldn't it be better to skip this library render if there aren't any URIs?

Can you explain how are you using this library? Does the user load the URIs? How does it work?

**Comment by caranicas** [comment]
My intention is be to give the user the option, where they could either use some built in search tools to get a URI, or give them the ability to sync with spotify if they wanted to use the vastly better UI, and pic songs from playlists. 

The issue i am running into that I can't sync with the external player without first instantiating the player `<SpotifyPlayer token={accessToken}/>` 

After the `READY`event I could check if their is a uri and if not instruct the user to sync with an external player (and hide it until they do), but when they do. Either manually, or thru the `syncExternalDevice` prop. there is no connected or disconnected event  so I have no way to know that things are ready to continue. 

based on some other things I've looked at, i think they solution would be add an await on this `this.player.connect()`  call https://github.com/gilbarbara/react-spotify-web-playback/blob/6f48ba717b673f0c43da227eb5829813d8ebaef7/src/index.tsx#L621

and then pass the result thru `handlePlayerStateChanges`

**Comment by gilbarbara** [comment]
Not sure what you mean by:
> sync with an external player (and hide it until they do)

Hide what? The whole player? The Play/Pause button?

The `this.player.connect();` would initialize the player but the READY event comes after that. That's why I don't care about the connect boolean. It can do anything until it's ready.

Anyway, since URIs is prop that you set it on the component, you already have access to it.

**Comment by caranicas** [comment]
Thanks for the quick responses :) 

I think I can outline the user flow that I'd like, and that might better explain it. 

1 - Click Login, do callback and get token. 
2 - Action page with an instantiated player (get 2 callbacks for `status_update`, INITIALIZING and READY)
3 - Prompt a modal "Select a song from the drop down (selecting a uri), or connect your Spotify app" 
4 - User opens Spotify app and connects their device. (no events)
5 - User returns to the page and the modal is gone and they can click the play button, or do other things on the page.   

Currently step 5 is impossible, because step 4 doesn't have any events. 

I have to wait for them to take that action, and I have no way to know when it is complete. They only thing I can do is tie into `player_update` and know that if it is playing it is connected. but I have other things I want my user to be able to do  on the page without having to start playing the music. 

Does that make more sense?

**Comment by gilbarbara** [comment]
hey @caranicas 

> 4 - User opens Spotify app and connects their device.

What is the `connect` part? Or the user just opens the app?

The device list won't be updated automatically.

The only sync in this library is for the `/player` endpoint when the user selects an external device and even in this case, the default interval is 5 seconds because I don't want to flood their API and get 429 error (Too Many Requests).

I could update the device list when the user clicks the devices menu, but I don't plan to add sync for this.
And there's no way to change the device programmatically. The user has to change it.
For example, I keep the Spotify app opened 24/7 on my desktop computer with loud speakers. I wouldn't like for an app to control it by mistake.

The external device is a fallback for unsupported browsers or transfer the URI context to a native app and kept listening even after you close the web player.

Also, if the user opens the Spotify app why it would use the player instead of the app and lose all the good features.

**Comment by caranicas** [comment]
sorry if step 4 wasn't clear. But yes I was referring to opening the Spotify app on my desktop. and selecting my named player in the "Connect to a device" menu. 

> The only sync in this library is for the /player endpoint when the user selects an external device

this sounds like what I want. what do I need to listen for to know when this connection to an external device has occurred?

**Comment by gilbarbara** [comment]
`event.type === TYPE.DEVICE`
