### ISSUE TITLE
addition of seek, noticed some bugs

### ISSUE THREAD

**Issue by kristinyim** [gilbarbara/react-spotify-web-playback#6]
Thank you so much for this making this! I made a simple react app with the Spotify API and am trying to use this instead of the SDK to finish it off. Here's where I use it in my project: https://github.com/kristinyim/smookify/blob/master/src/components/Study.js#L50 

A couple of questions:

1. For my specific project, I need to be able to seek to a random part of the song. Would it be possible to add this feature? 

2. Sometimes on initialization, pressing the Play button doesn't start the music and you get a 403 error. If you go to devices and reselect the Spotify Web Player then things work fine. I think the 403 is because its currently being played on another device. To recreate, try having multiple tabs open.

3. The URIs list isn't working for me. It just starts playing whatever song was last played on another device, disregarding the URI list I send it. Maybe this is related to (2)?

Thanks for your help in advance!

**Comment by gilbarbara** [comment]
Hello,

Just to clarify this component uses Spotify's Web Playback SDK. This is just a UI on top of it.

1 - This is not something I plan to add but feel free to submit a PR.

2 - 403 is an authorization error which probably means your token has expired. It's only valid for an hour, so you'll need to validate and renew the token by yourself.

3 - Probably not, since 403 is authorization error.
You can check this [codesandbox](https://codesandbox.io/s/react-spotify-web-playback-demo-dye1g) for the demo source code.
Since the preview panel runs on an iframe, the player **DOESN'T** work in it.
That's why the demo isn't hosted there and you must open the preview in a new window to work.
